services:
  postgres:
    image: postgres:16
    container_name: ${POSTGRES__HOST}
    environment:
      POSTGRES_DB: ${POSTGRES__DATABASE}
      POSTGRES_USER: ${POSTGRES__USER}
      POSTGRES_PASSWORD: ${POSTGRES__PASSWORD}
    expose:
      - ${POSTGRES__PORT}
    healthcheck:
      test: pg_isready -U ${POSTGRES__USER} -d ${POSTGRES__DATABASE}
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pg_data01:/var/lib/postgresql/data

  tg-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tg-bot
    env_file:
      - .env
    depends_on:
      - postgres
    restart: on-failure
    volumes:
      - tg_bot_logs:/app/logs

volumes:
  pg_data01:
  tg_bot_logs:
