"""00001_initial

Revision ID: 00001
Revises: 
Create Date: 2025-02-27 18:02:34.663997

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.core.config import app_settings

# revision identifiers, used by Alembic.
revision: str = "00001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

schema = app_settings.postgres.schema_


def upgrade() -> None:
    op.execute(f"CREATE SCHEMA {schema};")
    op.create_table(
        "category",
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        schema=schema,
    )
    op.create_table(
        "subcategory",
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"], [f"{schema}.category.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        schema=schema,
    )
    op.create_table(
        "product",
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("price", sa.Numeric(precision=19, scale=2), nullable=False),
        sa.Column("photo_link", sa.String(), nullable=True),
        sa.Column("subcategory_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["subcategory_id"], [f"{schema}.subcategory.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        schema=schema,
    )
    op.create_table(
        "cart_item",
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"], [f"{schema}.product.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema=schema,
    )
    op.create_table(
        "order",
        sa.Column("creation_dttm", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("payment_amount", sa.Numeric(precision=19, scale=2), nullable=False),
        sa.Column("payment_link", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema=schema,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cart_item", schema=schema)
    op.drop_table("product", schema=schema)
    op.drop_table("subcategory", schema=schema)
    op.drop_table("category", schema=schema)
    op.drop_table("order", schema=schema)
    op.execute(f"DROP SCHEMA {schema} CASCADE;")
    # ### end Alembic commands ###
